export const GOOGLE_SIGNIN = 'GOOGLE_SIGNIN';
export const GOOGLE_SIGNIN_RESULT = 'GOOGLE_SIGNIN_RESULT';
export const GET_GOOGLE_TOKENS = 'GET_GOOGLE_TOKENS';

export const REFRESH_GOOGLE_TOKENS = 'REFRESH_GOOGLE_TOKENS';
export const REFRESH_GOOGLE_TOKENS_LOADING = 'REFRESH_GOOGLE_TOKENS_LOADING';
export const GET_REFRESH_GOOGLE_TOKENS = 'GET_REFRESH_GOOGLE_TOKENS';


export const USER_SIGNIN = 'USER_SIGNIN';